#pragma once

#undef EE_HANDS
#define MASTER_LEFT
#define USE_SERIAL
#define SOFT_SERIAL_PIN D2
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_LED_STATE_ENABLE
#define RGBLIGHT_SPLIT
#define RGBLED_NUM 27
#define RGBLED_SPLIT {14, 13}
#ifdef RGBLIGHT_LED_COUNT
#  undef RGBLIGHT_LED_COUNT
#endif
#define RGBLIGHT_LED_COUNT RGBLED_NUM
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_LIMIT_VAL 180
#define RGBLIGHT_HUE_STEP 8
#define RGBLIGHT_SAT_STEP 8
#define RGBLIGHT_VAL_STEP 8
#define RGBLIGHT_SLEEP
